[package]
authors = ["Carter Reeb <reebcw@pm.me>"]
edition = "2021"
name = "dolomite-core"
version = "0.1.0"

[dependencies]
anyhow = "1"
nom = "7"
nom_locate = {git = "https://github.com/fflorent/nom_locate"}
log = "0.4"
pretty_env_logger = "0.4"
dolomite-logger = {path = "../logger"}