[package]
authors = ["Carter Reeb <reebcw@pm.me>"]
edition = "2018"
name = "dolomite-collector"
version = "0.1.0"

[dependencies]
anyhow = "1"
bincode = "2.0.0-alpha.0"
json5 = "0.4"
serde = "1"
serde_derive = "1"
